language: scala

scala:
  - 2.12.8

jdk:
  - openjdk9
notifications:
  # Email notifications are disabled, the README contains a link to the CI build status.
  # See http://about.travis-ci.org/docs/user/build-configuration/ to configure
  email: false

script:
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
