language: scala

scala:
  - 2.13.1

jdk:
  - openjdk9

notifications:
  # Email notifications are disabled, the README contains a link to the CI build status.
  # See http://about.travis-ci.org/docs/user/build-configuration/ to configure
  email: false

script:
  - sbt clean test
  # TODO: until sbt-coverage is on 2.13.1 - sbt clean coverage test coverageReport

#after_success:
#  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: sbt "release with-defaults"
  on:
    branch: master

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - rm -f $HOME/.ivy2/.sbt.ivy.lock

# speedup sbt builds
cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
