# avoid infinite loop when travis is publishing a new version
if: type = push AND commit_message !~ /Setting/

language: scala

scala:
  - 2.13.1

jdk:
  - openjdk9

services:
  - docker

addons:
  apt:
    packages:
      - sshpass

notifications:
  # Email notifications are disabled, the README contains a link to the CI build status.
  # See http://about.travis-ci.org/docs/user/build-configuration/ to configure
  email: false

script:
  - sbt clean test
  # TODO: until sbt-coverage is on 2.13.1 - sbt clean coverage test coverageReport

after_success:
  - echo "releasing on master branch only ..."
  - if [[ "$TRAVIS_BRANCH" = "master" ]] && [[ "$TRAVIS_COMMIT_MESSAGE" != *"Setting version"* ]]; then bash ./script/release_travis.sh; fi
#  - bash <(curl -s https://codecov.io/bash)
