# avoid infinite loop when travis is publishing a new version
if: type = push AND commit_message !~ /Setting/

language: scala

scala:
  - 2.13.1

jdk:
  - openjdk9

services:
  - docker

addons:
  ssh_known_hosts: velocorner.com

notifications:
  # Email notifications are disabled, the README contains a link to the CI build status.
  # See http://about.travis-ci.org/docs/user/build-configuration/ to configure
  email: false

before_install:
  - openssl aes-256-cbc -K $encrypted_fa718eafddd5_key -iv $encrypted_fa718eafddd5_iv -in script/deploy_key.enc -out script/deploy_key -d

script:
  - sbt clean test
  # TODO: until sbt-coverage is on 2.13.1 - sbt clean coverage test coverageReport

after_success:
  - echo "releasing on master branch only ..."
  - if [[ "$TRAVIS_BRANCH" = "master" ]] && [[ "$TRAVIS_COMMIT_MESSAGE" != *"Setting version"* ]]; then bash ./script/release_travis.sh; fi
#  - bash <(curl -s https://codecov.io/bash)
