language: scala

scala:
  - 2.13.1

jdk:
  - openjdk9

notifications:
  # Email notifications are disabled, the README contains a link to the CI build status.
  # See http://about.travis-ci.org/docs/user/build-configuration/ to configure
  email: false

script:
  - sbt clean test
  # TODO: until sbt-coverage is on 2.13.1 - sbt clean coverage test coverageReport

after_success:
  - echo "testing succeeded"
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then sbt "release with-defaults"; fi
#  - bash <(curl -s https://codecov.io/bash)
