---
  openapi: "3.0.0"
  info:
    title: "Velocorner API"
    description: "Public API for cycling statistics"
    contact:
      name: "Velocorner API"
      email: "velocorner.com@gmail.com"
  consumes:
    - application/json
  produces:
    - application/json